#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.18063
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Sample.MyAndroid.Resource", IsApplication=true)]

namespace Sample.MyAndroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::ZXing.Mobile.Resource.Id.contentFrame = global::Sample.MyAndroid.Resource.Id.contentFrame;
			global::ZXing.Mobile.Resource.Layout.zxingscanneractivitylayout = global::Sample.MyAndroid.Resource.Layout.zxingscanneractivitylayout;
			global::ZXing.Mobile.Resource.Layout.zxingscannerfragmentlayout = global::Sample.MyAndroid.Resource.Layout.zxingscannerfragmentlayout;
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int app_icon = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int monoandroidsplash = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int no_image = 2130837507;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060012
			public const int buttonZxingFlash = 2131099666;
			
			// aapt resource value: 0x7f060013
			public const int contentFrame = 2131099667;
			
			// aapt resource value: 0x7f060002
			public const int customImageToastImageView = 2131099650;
			
			// aapt resource value: 0x7f060000
			public const int customImageToastLinearLayoutMain = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int customImageToastTextViewCaption = 2131099651;
			
			// aapt resource value: 0x7f060001
			public const int customImageToastTextViewTitle = 2131099649;
			
			// aapt resource value: 0x7f06000d
			public const int linearLayout1 = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int linearLayout2 = 2131099664;
			
			// aapt resource value: 0x7f060008
			public const int mainButtonBook = 2131099656;
			
			// aapt resource value: 0x7f06000b
			public const int mainButtonCD = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int mainButtonDVD = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int mainButtonGame = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int mainButtonNew = 2131099658;
			
			// aapt resource value: 0x7f060005
			public const int mainImageViewPieChart = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int mainLinearLayoutBookAndGame = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int mainLinearLayoutCDAndDVD = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int relativeLayoutMain = 2131099652;
			
			// aapt resource value: 0x7f06000e
			public const int textView1 = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int textView2 = 2131099663;
			
			// aapt resource value: 0x7f060011
			public const int textView3 = 2131099665;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomImageToast = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int ZxingOverlay = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int zxingscanneractivitylayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int zxingscannerfragmentlayout = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f050000
			public const int Mono_Android_Theme_Splash = 2131034112;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
